package io.github.siemieniuk.votingsystems;

public enum VotingSystemType {
    FIRST_PAST_THE_POST,
    TWO_ROUND_SYSTEM,
    ANTI_PLURALITY,
    BORDA_COUNT,
    CONDORCET,
    BUCKLIN,
    APPROVAL_VOTING,
    SINGLE_NOT_TRANSFERABLE_VOTE,
    INSTANT_RUNOFF,
    COPELAND_RULE,
    KEMENY_RULE,
    KEMENY,
    MINIMAX,
    COOMBS,
    BALDWIN,
    DHONDT,
    SAINTE_LAGUE,
    HAMILTON,
    HARE_CLARK
}
